version: '3.8'

services:
  mtogo.orders:
    container_name: mtogo-emails
    image: mtogo.emails
    build:
      context: .
      dockerfile: src/EmailSender/Dockerfile
    ports:
      - "8087:80"
    networks:
      - kafka

networks:
  kafka:
    external: true